### PR TITLE
Added jet veto map for full 2024

### PR DESCRIPTION
**Pull request by ravindkv**
This PR introduces the jetvetomap covering all 2024 eras, replacing the earlier era-specific maps. Analysts are currently advised to use the following two maps together:

1. jetvetomap
2. jetvetomap_fpix

The `jetvetomap` excludes the faulty `fpix` region. To properly veto this region, the `jetvetomap_fpix` map must also be used.

We are in the process of deriving dedicated scale factors (SFs) for the fpix region. Once these SFs are available, analysts will no longer need to veto the `fpix` region. Instead, they will apply the scale factors directly, eliminating the need for the `jetvetomap_fpix` map in future analyses.

### CODE REVIEW

**Comment by ravindkv** [comment]
For your information, the ROOT file also contains additional veto maps. However, these are intended for use by JME experts only.

**Comment by dsavoiu** [comment]
HI @ravindkv, thank you for the PR! The veto map looks good to me, I just have one comment: could you rename the file to `Winter24Prompt24_2024BCDEFGHI.root` so it is clear from the name that it applied to the whole year?

**Comment by ravindkv** [comment]
Hi @dsavoiu , thank you for the comments. Sure, we have included the era names in the root file.

**Review by dsavoiu — APPROVED** [review]
Perfect, thanks for the prompt update @ravindkv! The PR looks good to merge now.

**Pull request merged**
